name: build-dataset

on:
  schedule:
    - cron:  '0 4 * * *'      # ogni giorno alle 04:00 UTC
  workflow_dispatch:          # oppure a mano 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Restore pip cache        
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python -m scraper.main

      - name: Upload full dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandiradar-full
          path: |
            bandi.csv
            bandi.json
            bandi.ics
            slices/
